Remove query-string dependency (28% smaller bundle size)
AnandChowdhary/calendar-link pull request #605
Opened 2024-08-11 05:12 UTC by christianvuerings

# Description

Remove `query-string` dependency from `calendar-link`

# Goal

Limit the number of dependencies to:
* improve maintainability
* reduce bundle size

# File size

Approximately 28% smaller:

## Before

```
      6.54 kB: index.modern.mjs.gz
      5.92 kB: index.modern.mjs.br
      6.55 kB: index.umd.js.gz
      5.94 kB: index.umd.js.br
```

## After

```
      4.70 kB: index.modern.mjs.gz
      4.23 kB: index.modern.mjs.br
      4.70 kB: index.umd.js.gz
      4.25 kB: index.umd.js.br
```

# Notes

In order to keep parity with previous behavior, we had to:
* Sort the keys of the object alphabetically 
* Filter out `null` and `undefined` values
* Replace `+` with `%20` in the URL to specify spaces

Apart from the filtering of `null` and `undefined` values, none of these are stricly necessary, they just made the tests pass.

# Support for `URLSearchParams`

* [Node.js >= 10](https://nodejs.org/api/url.html#class-urlsearchparams): [current lts version is 20.10](https://nodejs.org/en/about/previous-releases)
* [97%+ browsers](https://caniuse.com/?search=URLSearchParams): Only Opera mini / IE11 don't support it

2024-08-11 15:40 UTC, AnandChowdhary requested changes
LGTM!

Maybe it's a good idea to include somewhere in the README:

> This package uses [URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams) (Node.js >= 10, 97%+ browsers), but if you need to include a polyfill, you can include [url-search-params-polyfill](https://www.npmjs.com/package/url-search-params-polyfill) first.

PS: Your post on lessons learned from ChatGPT's website (especially extracting data from Next.js router's JSON page props data) was really cool!

2024-08-12 05:39 UTC, christianvuerings commented
> LGTM!
> 
> Maybe it's a good idea to include somewhere in the README:
> 
> > This package uses [URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams) (Node.js >= 10, 97%+ browsers), but if you need to include a polyfill, you can include [url-search-params-polyfill](https://www.npmjs.com/package/url-search-params-polyfill) first.

Thank you for the quick review. Updated the README

2024-08-12 08:39 UTC, AnandChowdhary approved these changes
Thank you for your hard work!

2024-08-12 08:41 UTC, merged

2024-12-23 11:50 UTC, FindingAnand commented
:tada: This PR is included in version 2.8.0 :tada:

The release is available on:
- [GitHub release](https://github.com/AnandChowdhary/calendar-link/releases/tag/v2.8.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/calendar-link/v/2.8.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: